<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?php echo APP::config('nazivAPP'); ?></title>
<link rel="stylesheet" href="<?php echo APP::config('url'); ?>public/css/foundation.css">
<link rel="stylesheet" href="<?php echo APP::config('url'); ?>public/css/app.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">