<!-- Početak izbornik -->
<div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
<button class="menu-icon" type="button" data-toggle></button>
<div class="title-bar-title"><?php echo APP::config('nazivAPP'); ?></div>
</div>

<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text show-for-large">
                    <?php echo APP::config('nazivAPP'); ?>
                </li>
        <li><a href="/">Početna</a></li>
        <li><a href="/index/onama">o nama</a></li>
        <li><a href="/index/kontakt">Kontakt</a></li>
        
        
  
        </ul>
    </div>
    
</div>
<!-- Kraj izbornik -->